server:
  port: 8080
  context-path: /demo/
  
spring:
      profiles:
        active: dev

info:
    status: ok  

springfox:
    documentation:
        swagger:
            v2:
                path: /swagger.json
mybatis:
  type-aliases-package: com.hand.*.access.vo
  mapper-locations: classpath*:com/hand/*/access/dao/*Dao.xml